# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xci
# IP: The module: 'clk_wiz_hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.gen/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.gen/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.gen/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.srcs/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xci
# IP: The module: 'clk_wiz_hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.gen/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.gen/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ja/Documents/ucisw/UCISW2-PROJEKT-main/ucisw2.gen/sources_1/ip/clk_wiz_hdmi/clk_wiz_hdmi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
